version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  zookeeper:
    image: wurstmeister/zookeeper  
    restart: unless-stopped  
    ports: ["2181:2181"]

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports: ["9092:9092"]
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka   
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test_topic:1:1

  producer:
    build: ./services/producer
    restart: unless-stopped
    ports: ["8084:8084"]
    environment:  
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
     
  consumer:
    build: ./services/consumer
    restart: unless-stopped
    ports: ["8083:8083"]
    environment: 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
